---
language: node_js
node_js:
  - "7"
  - "8"

sudo: false

cache: false

before_install:
  - npm i -g npm
  - cd frontend

before_install:
  - npm install -g npm
install:
  - npm install

script:
  - npm test
